### ISSUE TITLE
已经安装了scapy，但是依然提示未安装scapy，运行的时候有报错。

### ISSUE THREAD

**Issue by littleheary** [naozibuhao/QQLocation#1]
监听中,请开始QQ通话(电话/视频都可以)...Ctrl+C 结束监听
Traceback (most recent call last):
  File "QQLocation.py", line 122, in <module>
    Menu()
  File "QQLocation.py", line 91, in Menu
    runGo()
  File "QQLocation.py", line 105, in runGo
    compatibility.log_runtime = log_runtime
NameError: global name 'log_runtime' is not defined

**Comment by naozibuhao** [comment]
你可以重新装一下，我这边的开发环境是 win8.1 python 2.7 其他的两个依赖包都是 pip安装的

**Comment by naozibuhao** [comment]
是不是没有安装 wpcap 

你们可以参考：http://www.jb51.net/os/windows/378774.html
